data = [
    {"name": "Cristiano Ronaldo", "follower_count": 640, "description": "Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "follower_count": 500, "description": "Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "follower_count": 430, "description": "Singer and actress", "country": "United States"},
    {"name": "Kylie Jenner", "follower_count": 400, "description": "Reality TV personality", "country": "United States"},
    {"name": "Dwayne Johnson", "follower_count": 395, "description": "Actor and wrestler", "country": "United States"},
    {"name": "Ariana Grande", "follower_count": 380, "description": "Singer", "country": "United States"},
    {"name": "Kim Kardashian", "follower_count": 360, "description": "Reality TV personality", "country": "United States"},
    {"name": "Beyonce", "follower_count": 320, "description": "Singer", "country": "United States"},
    {"name": "Justin Bieber", "follower_count": 295, "description": "Singer", "country": "Canada"},
    {"name": "Taylor Swift", "follower_count": 290, "description": "Singer", "country": "United States"},
    {"name": "Virat Kohli", "follower_count": 270, "description": "Cricketer", "country": "India"},
    {"name": "Neymar", "follower_count": 230, "description": "Footballer", "country": "Brazil"},
    {"name": "Zendaya", "follower_count": 185, "description": "Actress and singer", "country": "United States"},
    {"name": "Shakira", "follower_count": 190, "description": "Singer", "country": "Colombia"},
    {"name": "LeBron James", "follower_count": 160, "description": "Basketball player", "country": "United States"},
    {"name": "Rihanna", "follower_count": 150, "description": "Singer and businesswoman", "country": "Barbados"},
    {"name": "Billie Eilish", "follower_count": 120, "description": "Singer", "country": "United States"},
    {"name": "Narendra Modi", "follower_count": 95, "description": "Prime Minister", "country": "India"},
    {"name": "Emma Watson", "follower_count": 75, "description": "Actress", "country": "United Kingdom"},
    {"name": "Chris Hemsworth", "follower_count": 60, "description": "Actor", "country": "Australia"},
    {"name": "Tom Holland", "follower_count": 68, "description": "Actor", "country": "United Kingdom"},
    {"name": "Robert Downey Jr.", "follower_count": 57, "description": "Actor", "country": "United States"},
    {"name": "Scarlett Johansson", "follower_count": 35, "description": "Actress", "country": "United States"},
    {"name": "Will Smith", "follower_count": 64, "description": "Actor and rapper", "country": "United States"},
    {"name": "Drake", "follower_count": 145, "description": "Rapper", "country": "Canada"},
    {"name": "Katy Perry", "follower_count": 205, "description": "Singer", "country": "United States"},
    {"name": "Jennifer Lopez", "follower_count": 250, "description": "Singer and actress", "country": "United States"},
    {"name": "Miley Cyrus", "follower_count": 215, "description": "Singer", "country": "United States"},
    {"name": "Kevin Hart", "follower_count": 180, "description": "Comedian and actor", "country": "United States"},
    {"name": "Priyanka Chopra", "follower_count": 92, "description": "Actress", "country": "India"},
    {"name": "Alia Bhatt", "follower_count": 86, "description": "Actress", "country": "India"},
    {"name": "Deepika Padukone", "follower_count": 80, "description": "Actress", "country": "India"},
    {"name": "Shraddha Kapoor", "follower_count": 94, "description": "Actress", "country": "India"},
    {"name": "Akshay Kumar", "follower_count": 67, "description": "Actor", "country": "India"},
    {"name": "Salman Khan", "follower_count": 69, "description": "Actor", "country": "India"},
    {"name": "Shah Rukh Khan", "follower_count": 48, "description": "Actor", "country": "India"},
    {"name": "Anushka Sharma", "follower_count": 68, "description": "Actress", "country": "India"},
    {"name": "Sachin Tendulkar", "follower_count": 48, "description": "Cricketer", "country": "India"},
    {"name": "MS Dhoni", "follower_count": 50, "description": "Cricketer", "country": "India"},
    {"name": "Rohit Sharma", "follower_count": 42, "description": "Cricketer", "country": "India"},
    {"name": "Hardik Pandya", "follower_count": 39, "description": "Cricketer", "country": "India"},
    {"name": "Ranveer Singh", "follower_count": 47, "description": "Actor", "country": "India"},
    {"name": "Snoop Dogg", "follower_count": 88, "description": "Rapper", "country": "United States"},
    {"name": "Ed Sheeran", "follower_count": 48, "description": "Singer", "country": "United Kingdom"},
    {"name": "Bruno Mars", "follower_count": 33, "description": "Singer", "country": "United States"},
    {"name": "Gal Gadot", "follower_count": 108, "description": "Actress", "country": "Israel"},
    {"name": "Jason Momoa", "follower_count": 17, "description": "Actor", "country": "United States"},
    {"name": "Chris Evans", "follower_count": 20, "description": "Actor", "country": "United States"},
    {"name": "Mark Zuckerberg", "follower_count": 15, "description": "Entrepreneur", "country": "United States"},
    {"name": "Elon Musk", "follower_count": 12, "description": "Entrepreneur", "country": "United States"}
]
print(data[5]["name"])